package install

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/blamely/blamely/internal/config"
)

// InstallGitHook sets core.hooksPath to ~/.blamely/git-hooks (globally) and
// writes a post-commit script that invokes `blamely attribute` and then chains
// to any repo-local .git/hooks/post-commit. Returns the previous value of
// core.hooksPath (empty if unset).
func InstallGitHook(binaryPath string) (priorHooksPath string, hadPrior bool, err error) {
	hooksDir, err := config.GitHooksDir()
	if err != nil {
		return "", false, err
	}
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return "", false, fmt.Errorf("mkdir %s: %w", hooksDir, err)
	}

	priorHooksPath, hadPrior = readGlobalConfig("core.hooksPath")

	scriptPath := filepath.Join(hooksDir, postCommitName())
	if err := writePostCommitScript(scriptPath, binaryPath); err != nil {
		return priorHooksPath, hadPrior, err
	}

	prePushPath := filepath.Join(hooksDir, "pre-push")
	if err := writePrePushScript(prePushPath); err != nil {
		return priorHooksPath, hadPrior, err
	}

	postRewritePath := filepath.Join(hooksDir, "post-rewrite")
	if err := writePostRewriteScript(postRewritePath, binaryPath); err != nil {
		return priorHooksPath, hadPrior, err
	}

	postMergePath := filepath.Join(hooksDir, "post-merge")
	if err := writePostMergeScript(postMergePath, binaryPath); err != nil {
		return priorHooksPath, hadPrior, err
	}

	if err := setGlobalConfig("core.hooksPath", hooksDir); err != nil {
		return priorHooksPath, hadPrior, err
	}
	return priorHooksPath, hadPrior, nil
}

// UninstallGitHook restores the previous core.hooksPath (or unsets it if there
// was none), then removes our hooks dir.
func UninstallGitHook(prior string, hadPrior bool) error {
	if hadPrior {
		if err := setGlobalConfig("core.hooksPath", prior); err != nil {
			return err
		}
	} else {
		_ = unsetGlobalConfig("core.hooksPath")
	}
	dir, err := config.GitHooksDir()
	if err != nil {
		return err
	}
	return os.RemoveAll(dir)
}

func postCommitName() string {
	if runtime.GOOS == "windows" {
		// Git for Windows runs hooks in MSYS bash; the file is still named
		// `post-commit` without an extension.
		return "post-commit"
	}
	return "post-commit"
}

// writePostCommitScript renders a small shell script that:
//   1. Calls `blamely attribute <repo> <sha>` (best-effort, never blocks the commit).
//   2. Chains to a repo-local .git/hooks/post-commit if one exists.
func writePostCommitScript(path, binaryPath string) error {
	// We resolve the repo via `git rev-parse --show-toplevel` inside the script
	// so the same hook works for every repo on this machine.
	// The script:
	//   - Exits 0 if the binary is missing or `git rev-parse` fails, so a
	//     broken Blamely never blocks a user's commit.
	//   - Runs `blamely attribute` in the foreground (it's fast: reads SQLite
	//     and writes a git note) so the colored AI/Human bar prints inline.
	//   - Chains to a repo-local .git/hooks/post-commit afterwards, because
	//     core.hooksPath is global and we don't want to shadow user hooks.
	script := fmt.Sprintf(`#!/bin/sh
# Generated by Blamely. Do not edit by hand.
# Reverse via:  blamely uninstall

BLAMELY=%q
if [ ! -x "$BLAMELY" ]; then
    # 1. Try the stable install location under ~/.blamely/bin/.
    #    On Windows (Git bash) the binary is blamely.exe.
    STABLE="$HOME/.blamely/bin/blamely"
    [ -x "$STABLE" ] || STABLE="$STABLE.exe"
    if [ -x "$STABLE" ]; then
        BLAMELY="$STABLE"
    elif command -v blamely >/dev/null 2>&1; then
        # 2. Fall back to whatever is on $PATH.
        BLAMELY=$(command -v blamely)
    else
        # 3. Binary not found anywhere — skip silently so the commit is
        #    never blocked. Run "blamely install" to repair.
        exit 0
    fi
fi

SHA=$(git rev-parse HEAD 2>/dev/null) || exit 0
REPO=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0

# Synchronous: attribute is fast (SQLite read + git diff + git notes add).
# Output flows to the terminal so the user sees the AI/Human bar after committing.
"$BLAMELY" attribute "$REPO" "$SHA" || true

# Chain to a repo-local hook if present (we hijacked core.hooksPath). We never
# override the user's own hook: only a hook carrying a Blamely-generated marker
# is skipped (we've handled attribution above; re-running a stale Blamely hook
# would call an old binary and show a confusing error). Match strict markers so
# a user hook that merely mentions "blamely" is still run unchanged.
REPO_HOOK="$REPO/.git/hooks/post-commit"
if [ -x "$REPO_HOOK" ]; then
    if grep -qE "Generated by Blamely|Blamely hookRunner|refs/notes/blamely" "$REPO_HOOK" 2>/dev/null; then
        # Legacy Blamely-managed hook — skip to avoid double-run / stale binary.
        exit 0
    fi
    exec "$REPO_HOOK" "$@"
fi
exit 0
`, filepath.ToSlash(binaryPath))

	if err := atomicWrite(path, []byte(script), 0o755); err != nil {
		return err
	}
	return nil
}

// writePostMergeScript renders the post-merge hook: git runs it after a `git
// pull` or `git merge` brings new commits into the working branch.
//
// This is the only hook that fires for work someone ELSE committed, which is
// exactly the case a cloud agent produces — a Devin Cloud session edits a remote
// sandbox and its commits reach you by pull, so post-commit never runs and the
// lines would read as Human forever.
//
// The heavy lifting (working out the range, filtering to commits that actually
// carry an agent trailer, capping the batch) lives in `blamely attribute-merged`
// rather than in shell, so it is testable and so a huge pull cannot turn into a
// storm of subprocesses.
func writePostMergeScript(path, binaryPath string) error {
	script := fmt.Sprintf(`#!/bin/sh
# Generated by Blamely. Do not edit by hand.
# Reverse via:  blamely uninstall

BLAMELY=%q
if [ ! -x "$BLAMELY" ]; then
    STABLE="$HOME/.blamely/bin/blamely"
    [ -x "$STABLE" ] || STABLE="$STABLE.exe"
    if [ -x "$STABLE" ]; then
        BLAMELY="$STABLE"
    elif command -v blamely >/dev/null 2>&1; then
        BLAMELY=$(command -v blamely)
    else
        exit 0
    fi
fi

REPO=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0

# ORIG_HEAD is where the branch stood before the merge, so ORIG_HEAD..HEAD is
# exactly what this pull brought in. Missing on a first clone — skip then.
if git rev-parse --verify --quiet ORIG_HEAD >/dev/null 2>&1; then
    "$BLAMELY" attribute-merged "$REPO" "ORIG_HEAD..HEAD" >/dev/null 2>&1 || true
fi

# Chain to a repo-local hook if present (we hijacked core.hooksPath).
REPO_HOOK="$REPO/.git/hooks/post-merge"
if [ -x "$REPO_HOOK" ]; then
    if grep -qE "Generated by Blamely|Blamely hookRunner|refs/notes/blamely" "$REPO_HOOK" 2>/dev/null; then
        exit 0
    fi
    exec "$REPO_HOOK" "$@"
fi
exit 0
`, filepath.ToSlash(binaryPath))

	return atomicWrite(path, []byte(script), 0o755)
}

// writePrePushScript renders a shell script that pushes refs/notes/blamely to
// the same remote the user is pushing to, then chains to any repo-local
// .git/hooks/pre-push. The notes push is best-effort and never blocks the push.
//
// Hooks are installed globally via core.hooksPath; this script also reaps stale
// per-repo Blamely artifacts left by older installs (a repo-local .git/blamely
// runner and Blamely-managed .git/hooks/pre-push), which were both redundant
// and the source of an infinite pre-push recursion.
func writePrePushScript(path string) error {
	script := `#!/bin/sh
# Generated by Blamely. Do not edit by hand.
# Reverse via:  blamely uninstall

REMOTE="$1"

# Forward stdin to the chained hook (if any); buffer it first since we may
# need to pass it along after consuming it ourselves.
STDIN=$(cat)

# Push attribution notes to the same remote — silently ignore errors (remote
# may not accept notes refs, or there may be no notes yet).
# --no-verify is REQUIRED: core.hooksPath is set globally, so without it this
# nested push would re-trigger this same pre-push hook, recursing forever.
git push --no-verify "$REMOTE" refs/notes/blamely 2>/dev/null || true

REPO=$(git rev-parse --show-toplevel 2>/dev/null) || { printf '%s\n' "$STDIN"; exit 0; }

# Reap stale per-repo artifacts from older installs. Hooks are global now, so
# the per-repo runner directory is pure dead weight — remove it unconditionally.
rm -rf "$REPO/.git/blamely" 2>/dev/null || true

# Chain to a repo-local pre-push hook only if it is the user's own. We never
# touch user hooks: only a hook carrying a Blamely-generated marker is treated
# as a legacy leftover — deleted and not chained into (chaining is exactly what
# re-triggered this hook and recursed). Anything else is run unchanged.
REPO_HOOK="$REPO/.git/hooks/pre-push"
if [ -x "$REPO_HOOK" ]; then
    if grep -qE "Generated by Blamely|Blamely hookRunner|refs/notes/blamely" "$REPO_HOOK" 2>/dev/null; then
        rm -f "$REPO_HOOK" 2>/dev/null || true
        printf '%s\n' "$STDIN"
        exit 0
    fi
    printf '%s\n' "$STDIN" | exec "$REPO_HOOK" "$@"
fi
printf '%s\n' "$STDIN"
exit 0
`
	return atomicWrite(path, []byte(script), 0o755)
}

// writePostRewriteScript renders the post-rewrite hook: git invokes it after
// `commit --amend` / `rebase` with `old-sha new-sha` mapping lines on stdin —
// including the N→1 lines of an interactive-rebase squash/fixup. The script
// forwards that mapping to `blamely post-rewrite`, which rebuilds a single
// valid note for each squash target (git's default note copy concatenates the
// folded commits' JSON notes into an unparsable blob). Best-effort throughout:
// a broken Blamely never breaks a user's rebase. Chains to a repo-local
// post-rewrite hook with the buffered stdin, mirroring writePrePushScript.
func writePostRewriteScript(path, binaryPath string) error {
	script := fmt.Sprintf(`#!/bin/sh
# Generated by Blamely. Do not edit by hand.
# Reverse via:  blamely uninstall

KIND="$1"

# Buffer stdin (old-sha new-sha pairs): we consume it AND chain it onward.
STDIN=$(cat)

BLAMELY=%q
if [ ! -x "$BLAMELY" ]; then
    STABLE="$HOME/.blamely/bin/blamely"
    if [ -x "$STABLE" ]; then
        BLAMELY="$STABLE"
    elif command -v blamely >/dev/null 2>&1; then
        BLAMELY=$(command -v blamely)
    else
        BLAMELY=""
    fi
fi

REPO=$(git rev-parse --show-toplevel 2>/dev/null) || { exit 0; }

if [ -n "$BLAMELY" ]; then
    printf '%%s\n' "$STDIN" | "$BLAMELY" post-rewrite "$REPO" "$KIND" 2>/dev/null || true
fi

# Chain to a repo-local post-rewrite hook if it is the user's own.
REPO_HOOK="$REPO/.git/hooks/post-rewrite"
if [ -x "$REPO_HOOK" ]; then
    if grep -qE "Generated by Blamely|Blamely hookRunner|refs/notes/blamely" "$REPO_HOOK" 2>/dev/null; then
        exit 0
    fi
    printf '%%s\n' "$STDIN" | exec "$REPO_HOOK" "$@"
fi
exit 0
`, filepath.ToSlash(binaryPath))
	return atomicWrite(path, []byte(script), 0o755)
}

// RemoveLegacyRepoHooks deletes per-repo Blamely artifacts left by older
// installs: the .git/blamely runner directory and any Blamely-managed
// .git/hooks/{pre-push,post-commit}. With core.hooksPath set globally these
// are redundant, and the legacy pre-push runner caused an infinite recursion
// (a bare `git push refs/notes/blamely` re-triggered the global hook).
//
// It is best-effort and never errors out: callers run it on the hot path of a
// commit, so it must never block. User-authored repo hooks (those without a
// Blamely marker) are left untouched.
//
// It removes the legacy contents of .git/blamely individually but PRESERVES the
// Attribution working logs (.git/blamely/working_logs): this runs at the start
// of `blamely attribute` (the post-commit hook), which reads the working log a
// moment later to write the note — a wholesale RemoveAll here would wipe it first.
func RemoveLegacyRepoHooks(repoRoot string) {
	gitDir, err := gitDirFor(repoRoot)
	if err != nil {
		return
	}
	blamelyDir := filepath.Join(gitDir, "blamely")
	if entries, derr := os.ReadDir(blamelyDir); derr == nil {
		for _, e := range entries {
			if e.Name() == "working_logs" {
				continue // Attribution state — not a legacy artifact
			}
			_ = os.RemoveAll(filepath.Join(blamelyDir, e.Name()))
		}
		// If nothing remains (no working logs), drop the now-empty dir too, so a
		// repo with no attribution state ends up exactly as before (.git/blamely gone).
		if rem, rerr := os.ReadDir(blamelyDir); rerr == nil && len(rem) == 0 {
			_ = os.Remove(blamelyDir)
		}
	}
	for _, name := range []string{"pre-push", "post-commit"} {
		hookPath := filepath.Join(gitDir, "hooks", name)
		if isBlamelyManagedHook(hookPath) {
			_ = os.Remove(hookPath)
		}
	}
}

// gitDirFor resolves the .git directory for repoRoot, handling worktrees and
// submodules where .git is a file pointing elsewhere.
func gitDirFor(repoRoot string) (string, error) {
	out, err := exec.Command("git", "-C", repoRoot, "rev-parse", "--git-dir").Output()
	if err != nil {
		return "", err
	}
	dir := strings.TrimSpace(string(out))
	if dir == "" {
		return "", errors.New("empty git dir")
	}
	if !filepath.IsAbs(dir) {
		dir = filepath.Join(repoRoot, dir)
	}
	return dir, nil
}

// isBlamelyManagedHook reports whether the file at path is a hook script
// generated by Blamely (current or legacy), keyed off markers unique to our
// generated scripts so we never delete a user's own hook.
func isBlamelyManagedHook(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	body := string(data)
	for _, marker := range []string{"Generated by Blamely", "Blamely hookRunner", "refs/notes/blamely"} {
		if strings.Contains(body, marker) {
			return true
		}
	}
	return false
}

func readGlobalConfig(key string) (value string, present bool) {
	out, err := exec.Command("git", "config", "--global", "--get", key).Output()
	if err != nil {
		// `git config --get` exits 1 when the key isn't set.
		var ee *exec.ExitError
		if errors.As(err, &ee) && ee.ExitCode() == 1 {
			return "", false
		}
		return "", false
	}
	return strings.TrimSpace(string(out)), true
}

func setGlobalConfig(key, value string) error {
	cmd := exec.Command("git", "config", "--global", key, value)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git config --global %s %q: %v (%s)", key, value, err, strings.TrimSpace(stderr.String()))
	}
	return nil
}

func unsetGlobalConfig(key string) error {
	cmd := exec.Command("git", "config", "--global", "--unset", key)
	// Exit code 5 = "no such variable" — fine.
	if err := cmd.Run(); err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) && (ee.ExitCode() == 5 || ee.ExitCode() == 1) {
			return nil
		}
		return err
	}
	return nil
}
